version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  seismic_drs:
    build:
      context: ./seismic_drs
      dockerfile: Dockerfile_seismic_drs
    container_name: seismic_drs
    depends_on:
      - kafka
    ports:
      - "8001:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka_network

  data_processor:
    build:
      context: ./data_processor
      dockerfile: Dockerfile_data_processor
    container_name: data_processor
    depends_on:
      - kafka
    ports:
      - "8002:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
